- name: variables
  hosts: localhost
  vars: 
    Course: "Ansible"
    Trainer: "Shivakumar"
    Duration: "120hrs"
  tasks:
  - name: print override information
    vars: #Task level variable, every time task level variables are 1st preference
      Course: "Devops"
    ansible.builtin.debug:
      msg: "Hi, we are learning {{Course}} from Trainer  {{Trainer}}, Duration is {{Duration}}." 
  
  - name: print information
    ansible.builtin.debug:
      msg: "Hi, we are learning {{Course}} from Trainer  {{Trainer}}, Duration is {{Duration}}." 