- name: variables from files
  hosts: localhost
  tasks:
  - name: print information
    ansible.builtin.debug:
      msg: "Hi, we are learning {{Cource}} from Trainer  {{Trainer}}, Duration is {{Duration}}."