- name : data types
  hosts: localhost
  vars :
  - Course: Devops with AWS #string
    Tools: #List
      - Linux
      - shellscript
      - Ansible
    Experience:
      Devops: 3
      AWS: 2
      Docker: 1
    RealProject: true #boolean
  tasks:
  - name: print variables
    ansible.builtin.debug:
      msg: "Course: {{Course}}, Tools covered: {{Tools}}, Experiencne is: {{Experience}}, is real project{{RealProject}}"

