- name: default value
  hosts: localhost
  tasks:
  - name: print default value
    ansible.builtin.debug:
      msg: "Hello {{ Course | default('Ansible') }}"

- name: upper case
  hosts: localhost
  vars:
    greeting: "Hello, GoodMorning"
    numbers: [1,2,3,4,5,6,4,3,2,1]
  tasks:
  - name: convert into uppercase
    ansible.builtin.debug:
      msg: "{{greeting | upper}}"
  - name: convert into lowercase
    ansible.builtin.debug:
      msg: "{{greeting | lower}}"
  - name: remove duplicates
    ansible.builtin.debug:
      msg: "{{numbers | unique}}"
  
